package(default_visibility=["//visibility:public"])

cc_library(
    name = "macros",
    hdrs = ["macros.h"],
)

cc_library(
    name = "alignment",
    hdrs = ["alignment.h"],
    srcs = ["alignment.c"],
)